# Global settings applied to the whole site.
# “base” is directory to change to before starting build, and
# “publish” is the directory to publish (relative to root of your repo).
# “command” is your build command.

[build]
  base    = ""
  publish = "build"
  command = "REACT_APP_STAGE=dev npm run build"

# Master branch pushes
[context.production]
  command = "REACT_APP_STAGE=dev npm run build"

# Pull requests
[context.deploy-preview]
  command = "REACT_APP_STAGE=dev npm run build"

# Pushes to branches other than master
[context.branch-deploy]
  command = "REACT_APP_STAGE=dev npm run build"

# Always redirect any request to our index.html
# and return the status code 200.
[[redirects]]
    from    = "/*"
    to      = "/index.html"
    status  = 200
